server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false  # This app is the server, it doesn't register itself
    fetch-registry: false        # It doesn't need to fetch other services
  server:
    wait-time-in-ms-when-sync-empty: 0
